# Generated by Django 5.0.3 on 2024-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_Name", models.CharField(max_length=100)),
                ("date_of_birth", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("address", models.TextField()),
            ],
        ),
    ]
